import type { Homework } from "./types"
export const mockHomeworkData: Homework[] = [
  {
    id: 1,
    due_date: "2024-12-15",
    vocab_matches: [
      { id: 1, arabic_word: "كتاب", hebrew_word: "ספר", homework: 1 },
      { id: 2, arabic_word: "قلم", hebrew_word: "עט", homework: 1 },
      { id: 3, arabic_word: "مدرسة", hebrew_word: "בית ספר", homework: 1 },
      { id: 4, arabic_word: "بيت", hebrew_word: "בית", homework: 1 },
      { id: 5, arabic_word: "ماء", hebrew_word: "מים", homework: 1 },
      { id: 6, arabic_word: "شمس", hebrew_word: "שמש", homework: 1 },
      { id: 7, arabic_word: "قمر", hebrew_word: "ירח", homework: 1 },
      { id: 8, arabic_word: "طاولة", hebrew_word: "שולחן", homework: 1 },
      { id: 9, arabic_word: "كرسي", hebrew_word: "כיסא", homework: 1 },
      { id: 10, arabic_word: "باب", hebrew_word: "דלת", homework: 1 },
      { id: 11, arabic_word: "نافذة", hebrew_word: "חלון", homework: 1 },
      { id: 12, arabic_word: "يد", hebrew_word: "יד", homework: 1 },
      { id: 13, arabic_word: "رأس", hebrew_word: "ראש", homework: 1 },
      { id: 14, arabic_word: "عين", hebrew_word: "עין", homework: 1 },
      { id: 15, arabic_word: "أنف", hebrew_word: "אף", homework: 1 },
    ],
    fill_in_blanks: [
      {
        id: 1,
        sentence: "أنا أقرأ ___ كل يوم.",
        options: ["كتاب", "قلم", "مدرسة"],
        correct_option: "كتاب",
        homework: 1,
      },
      {
        id: 2,
        sentence: "هذا ___ أزرق.",
        options: ["كتاب", "قلم", "مدرسة"],
        correct_option: "قلم",
        homework: 1,
      },
      {
        id: 3,
        sentence: "أذهب إلى ___ كل صباح.",
        options: ["كتاب", "قلم", "مدرسة"],
        correct_option: "مدرسة",
        homework: 1,
      },
      {
        id: 4,
        sentence: "أنا أعيش في ___ كبير.",
        options: ["بيت", "ماء", "شمس"],
        correct_option: "بيت",
        homework: 1,
      },
      {
        id: 5,
        sentence: "أشرب ___ كل يوم.",
        options: ["بيت", "ماء", "شمس"],
        correct_option: "ماء",
        homework: 1,
      },
      {
        id: 6,
        sentence: "ال___ مشرقة اليوم.",
        options: ["بيت", "ماء", "شمس"],
        correct_option: "شمس",
        homework: 1,
      },
      {
        id: 7,
        sentence: "ال___ منير في الليل.",
        options: ["قمر", "طاولة", "كرسي"],
        correct_option: "قمر",
        homework: 1,
      },
      {
        id: 8,
        sentence: "الكتاب على ___.",
        options: ["قمر", "طاولة", "كرسي"],
        correct_option: "طاولة",
        homework: 1,
      },
      {
        id: 9,
        sentence: "أجلس على ___.",
        options: ["قمر", "طاولة", "كرسي"],
        correct_option: "كرسي",
        homework: 1,
      },
      {
        id: 10,
        sentence: "أغلق ال___ عندما أخرج.",
        options: ["باب", "نافذة", "يد"],
        correct_option: "باب",
        homework: 1,
      },
      {
        id: 11,
        sentence: "أفتح ال___ في الصباح.",
        options: ["باب", "نافذة", "يد"],
        correct_option: "نافذة",
        homework: 1,
      },
      {
        id: 12,
        sentence: "أكتب بال___ اليمنى.",
        options: ["باب", "نافذة", "يد"],
        correct_option: "يد",
        homework: 1,
      },
      {
        id: 13,
        sentence: "ال___ فوق الرقبة.",
        options: ["رأس", "عين", "أنف"],
        correct_option: "رأس",
        homework: 1,
      },
      {
        id: 14,
        sentence: "أرى بال___.",
        options: ["رأس", "عين", "أنف"],
        correct_option: "عين",
        homework: 1,
      },
      {
        id: 15,
        sentence: "ال___ في وسط الوجه.",
        options: ["رأس", "عين", "أنف"],
        correct_option: "أنف",
        homework: 1,
      },
    ],
    grammatical_phenomenon: {
      id: 1,
      text: "בשיעור זה למדנו על המילים הבסיסיות בערבית ואיך להשתמש בהן במשפטים פשוטים.",
      homework: 1,
    },
  },
  {
    id: 2,
    due_date: "2025-01-01",
    vocab_matches: [
      { id: 1, arabic_word: "غرفة", hebrew_word: "חדר", homework: 2 },
      { id: 2, arabic_word: "جيران", hebrew_word: "שכנים", homework: 2 },
      { id: 3, arabic_word: "استمارة", hebrew_word: "טופס", homework: 2 },
      { id: 4, arabic_word: "طاولة", hebrew_word: "שולחן", homework: 2 },
      { id: 5, arabic_word: "كرسي", hebrew_word: "כיסא", homework: 2 },
      { id: 6, arabic_word: "محكمة", hebrew_word: "בית משפט", homework: 2 },
      { id: 7, arabic_word: "حكومة", hebrew_word: "ממשלה", homework: 2 },
      { id: 8, arabic_word: "بلدية", hebrew_word: "עירייה", homework: 2 },
      { id: 9, arabic_word: "مكتب", hebrew_word: "משרד", homework: 2 },
      { id: 10, arabic_word: "شقة", hebrew_word: "דירה", homework: 2 },
      { id: 11, arabic_word: "بناية", hebrew_word: "בניין", homework: 2 },
      { id: 12, arabic_word: "شارع", hebrew_word: "רחוב", homework: 2 },
      { id: 13, arabic_word: "مدينة", hebrew_word: "עיר", homework: 2 },
      { id: 14, arabic_word: "قرية", hebrew_word: "כפר", homework: 2 },
      { id: 15, arabic_word: "جمل", hebrew_word: "גמל", homework: 2 },
    ],
    fill_in_blanks: [
      {
        id: 1,
        sentence: "ليش الجيران ما بدهم ___؟",
        options: ["الطاولة", "الغرفة", "الكرسي"],
        correct_option: "الغرفة",
        homework: 2,
      },
      {
        id: 2,
        sentence: "أنا لازم أعمل ___ جديدة.",
        options: ["استمارة", "غرفة", "طاولة"],
        correct_option: "استمارة",
        homework: 2,
      },
      {
        id: 3,
        sentence: "الكتاب على ___.",
        options: ["الطاولة", "الكرسي", "الغرفة"],
        correct_option: "الطاولة",
        homework: 2,
      },
      {
        id: 4,
        sentence: "أنا بجلس على ___.",
        options: ["الطاولة", "الكرسي", "الغرفة"],
        correct_option: "الكرسي",
        homework: 2,
      },
      {
        id: 5,
        sentence: "رحت على ___ عشان أدفع المخالفة.",
        options: ["المحكمة", "الحكومة", "البلدية"],
        correct_option: "المحكمة",
        homework: 2,
      },
      {
        id: 6,
        sentence: "ال___ بتعمل قوانين جديدة.",
        options: ["المحكمة", "الحكومة", "البلدية"],
        correct_option: "الحكومة",
        homework: 2,
      },
      {
        id: 7,
        sentence: "رحت على ال___ عشان أدفع الأرنونا.",
        options: ["المحكمة", "الحكومة", "البلدية"],
        correct_option: "البلدية",
        homework: 2,
      },
      {
        id: 8,
        sentence: "أنا بشتغل في ___ كبير.",
        options: ["مكتب", "شقة", "بناية"],
        correct_option: "مكتب",
        homework: 2,
      },
      {
        id: 9,
        sentence: "أنا ساكن في ___ صغيرة.",
        options: ["مكتب", "شقة", "بناية"],
        correct_option: "شقة",
        homework: 2,
      },
      {
        id: 10,
        sentence: "ال___ الجديدة كبيرة كتير.",
        options: ["مكتب", "شقة", "بناية"],
        correct_option: "بناية",
        homework: 2,
      },
      {
        id: 11,
        sentence: "بيتي في ___ الرئيسي.",
        options: ["الشارع", "المدينة", "القرية"],
        correct_option: "الشارع",
        homework: 2,
      },
      {
        id: 12,
        sentence: "أنا بسكن في ___ القدس.",
        options: ["الشارع", "المدينة", "القرية"],
        correct_option: "المدينة",
        homework: 2,
      },
      {
        id: 13,
        sentence: "هو من ___ صغيرة في الشمال.",
        options: ["الشارع", "المدينة", "القرية"],
        correct_option: "القرية",
        homework: 2,
      },
      {
        id: 14,
        sentence: "شفت ___ في الصحراء.",
        options: ["الجمل", "الغرفة", "الجيران"],
        correct_option: "الجمل",
        homework: 2,
      },
      {
        id: 15,
        sentence: "أنا بستن جواب ___.",
        options: ["المحكمة", "الحكومة", "الطاولة"],
        correct_option: "المحكمة",
        homework: 2,
      },
    ],
    grammatical_phenomenon: {
      id: 1,
      text: "בשיעור זה למדנו על השימוש במילה 'ליש' שפירושה 'למה' בערבית מדוברת, ואיך לשאול שאלות עם מילה זו. כמו כן, למדנו מילים הקשורות למוסדות ציבוריים ולמגורים.",
      homework: 2,
    },
  },
]
